# Generated by Django 2.1.5 on 2019-02-01 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField()),
                ('adi', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 2, 1, 12, 18, 8, 639363, tzinfo=utc), verbose_name='date_created')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
