# Generated by Django 2.1.5 on 2019-03-06 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', max_length=250, null=True, upload_to='pictures')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Şəkillər',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productlar',
            options={'ordering': ['-id'], 'verbose_name': 'Mehsullar cedveli', 'verbose_name_plural': 'Mehsullar'},
        ),
        migrations.RemoveField(
            model_name='productlar',
            name='date_created',
        ),
        migrations.AddField(
            model_name='productlar',
            name='alis_qiymeti',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlar',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productlar',
            name='eyar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productlar',
            name='gram',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlar',
            name='mezenne',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productlar',
            name='miqdari',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlar',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productlar',
            name='publish_1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productlar',
            name='satis_qiymeti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='status',
            field=models.IntegerField(choices=[(1, 'Satisda'), (2, 'Satildi'), (3, 'İmtina edildi')], default=1),
        ),
        migrations.AddField(
            model_name='images',
            name='sekil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Productlar'),
        ),
    ]
