# Generated by Django 2.1.5 on 2019-03-07 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20190306_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlar',
            name='publish_1',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
