# Generated by Django 2.1.5 on 2019-02-01 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20190201_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlar',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 12, 20, 56, 729005, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
