# Generated by Django 2.1.5 on 2019-03-13 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20190307_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlar',
            name='adi',
            field=models.CharField(help_text='Məhsulun adını qeyd edin. ', max_length=250),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='alis_qiymeti',
            field=models.DecimalField(decimal_places=2, help_text='Məhsulu aldıgınız qiyməti qeyd edin. ', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='eyar',
            field=models.IntegerField(help_text='Məhsulun əyarını qeyd edin. ', null=True),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='gram',
            field=models.DecimalField(decimal_places=2, help_text='Qramı ilə bağlı məlumat daxil edin. ', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='kod',
            field=models.IntegerField(help_text='Məhsulun kodunu qeyd edin. '),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='mezenne',
            field=models.DecimalField(decimal_places=3, help_text='Bugünün məzənnəsinə uyğun yazın ', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='publish_1',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Tarixi qeyd edin zehmet olmasa. ', null=True),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='satis_qiymeti',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Məhsulu planlaşdırğınız satış qiymətini daxil edin ', max_digits=10, null=True),
        ),
    ]
