# Generated by Django 2.1.5 on 2019-02-01 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20190201_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlar',
            name='date_created',
        ),
        migrations.AddField(
            model_name='productlar',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
