# Generated by Django 2.1.5 on 2019-02-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20190201_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlar',
            options={'verbose_name': 'Mehsullar cedveli', 'verbose_name_plural': 'Mehsullar'},
        ),
        migrations.AddField(
            model_name='productlar',
            name='gram',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
