# Generated by Django 2.1.5 on 2019-03-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20190314_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='pictures'),
        ),
    ]
