# Generated by Django 2.1.5 on 2019-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20190314_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=250, null=True, upload_to='pictures'),
        ),
    ]
