# Generated by Django 2.1.5 on 2019-02-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_auto_20190203_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlar',
            options={'ordering': ['-id'], 'verbose_name': 'Mehsullar cedveli', 'verbose_name_plural': 'Mehsullar'},
        ),
        migrations.AddField(
            model_name='productlar',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='status',
            field=models.IntegerField(choices=[(1, 'Satisda'), (2, 'Satildi'), (3, 'İmtina edildi')], default=1),
        ),
    ]
