# Generated by Django 2.1.5 on 2019-02-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_auto_20190215_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlar',
            name='image',
        ),
    ]
