# Generated by Django 2.1.5 on 2019-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_remove_productlar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
