# Generated by Django 2.1.5 on 2019-02-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_auto_20190216_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
