# Generated by Django 2.1.5 on 2019-02-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlar',
            name='məzənnə',
            field=models.IntegerField(null=True),
        ),
    ]
