# Generated by Django 2.1.5 on 2019-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_auto_20190216_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlar',
            name='məzənnə',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='qiymeti',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
