# Generated by Django 2.1.5 on 2019-02-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Image',
            new_name='image',
        ),
    ]
