# Generated by Django 2.1.5 on 2019-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_auto_20190216_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-id'], 'verbose_name': 'Şəkil', 'verbose_name_plural': 'Şəkillər'},
        ),
        migrations.AddField(
            model_name='productlar',
            name='publish_1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=250, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='gram',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productlar',
            name='qiymeti',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
