# Generated by Django 2.1.5 on 2019-02-17 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_auto_20190217_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlar',
            name='publish_1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
