# Generated by Django 2.1.5 on 2019-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0020_auto_20190217_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlar',
            old_name='qiymeti',
            new_name='alis_qiymeti',
        ),
        migrations.AddField(
            model_name='productlar',
            name='satis_qiymeti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
