# Generated by Django 2.1.5 on 2019-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_auto_20190223_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='pictures'),
        ),
    ]
